# Generated by Django 5.1.1 on 2024-10-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selection', '0001_initial'),
        ('courses', '0003_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selection_registrations', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selection_user_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
