# Generated by Django 5.1.1 on 2024-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('max_capacity', models.PositiveIntegerField()),
                ('enrollment_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6)),
            ],
        ),
    ]
